### ISSUE TITLE
Enumerated type Gender shows errors when compiled 

### ISSUE THREAD

**Issue by zydsh** [zydsh/erp#6]
When attempting to create Employee:

if param.Gender =="Male"
		emp.Gender = Gender::Male;
elif param.Gender == "Female"
		emp.Gender = Gender::Female;
else
	LOG::LogInfo(message:"Gender type unrecognized." );	
	UI::Reply( msg:"Gender type unrecognized.", state:False);
end if;

The compiler gives me the following errors 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Deployment: Compilation failure: Compilation failure: 
[ERROR] /Users/ziyadalshaikh/git/hrm/Deployment/target/generated-sources/java/hrsystem/hr/main/impl/EmployeeImpl.java:[65,20] illegal start of expression
[ERROR] /Users/ziyadalshaikh/git/hrm/Deployment/target/generated-sources/java/hrsystem/hr/HrUI.java:[61,31] illegal start of expression
[ERROR] /Users/ziyadalshaikh/git/hrm/Deployment/target/generated-sources/java/hrsystem/hr/HrUI.java:[61,32] ';' expected
[ERROR] /Users/ziyadalshaikh/git/hrm/Deployment/target/generated-sources/java/hrsystem/hr/HrUI.java:[64,31] illegal start of expression
[ERROR] /Users/ziyadalshaikh/git/hrm/Deployment/target/generated-sources/java/hrsystem/hr/HrUI.java:[64,32] ';' expected

The generated code looks as follows:
 public void CreateEmployee( final int p_EmployeeID,  final int p_NationalID,  final String p_FirstName,  final String p_MiddleName,  final String p_LastName,  final int p_DateOfBirth,  final String p_Degree,  final String p_Gender ) throws XtumlException {
        Employee employee = context().Employee_instances().anyWhere(selected -> ((Employee)selected).getNationalID() == p_NationalID);
        if ( employee.isEmpty() ) {
            Employee emp = EmployeeImpl.create( context() );
            emp.setEmployeeID(p_EmployeeID);
            emp.setNationalID(p_NationalID);
            emp.setFirstName(p_FirstName);
            emp.setMiddleName(p_LastName);
            emp.setLastName(p_LastName);
            emp.setDateOfBirth(p_DateOfBirth);
            emp.setDegree(p_Degree);
            if ( StringUtil.equality(p_Gender, "Male") ) {
                emp.setGender(.);  //Line 61
            }
            else if ( StringUtil.equality(p_Gender, "Female") ) {
                emp.setGender(.);  //Line 64
            }
            else {
                context().LOG().LogInfo( "Gender type unrecognized." );
                context().UI().Reply( "Gender type unrecognized.", false );
            }
            context().LOG().LogInfo( "Employee added successfully." );
            context().UI().Reply( "Employee added successfully.", true );
        }
        else {
            context().LOG().LogInfo( "Adding employee is unsuccessful. National ID is registered for another employee." );
            context().UI().Reply( "Adding employee is unsuccessful. Employee already exists", false );
        }
    }

**Comment by johnrwolfe** [comment]
Does the model parse correctly?  I recommend getting in the habit of executing "Parse all activities" against each xtUML project and then ensuring the Problems view is empty before attempting to compile the model with Ciera.  Also, please consider using Verifier to run tests before compiling with Ciera.  You will likely save a great deal of time, as isolating model defects with Verifier is much faster and easier than chasing them in generated code.
In the current version (master) of the model, Employee.Gender is of type string, so attempting to set it to an enumerated value should produce an OAL parse error.  Also, in the current version of the model, it appears that the CreateEmployee port activity contains the results of an attempted merge, perhaps one that produced a merge conflict?  Notice "<<<<< HEAD", etc.

**Comment by zydsh** [comment]
It does parse correctly. But let me verify again. Because the same issue 'illegal start of expression' appeared again with another compilation.
